version: '2'

services:
  dev:
    image: schema-plugins-build
    build:
      context: .
      args:
        BUILDER_UID: 1000
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - './:/app'
